# Generated by Django 6.0.6 on 2026-06-21 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('movement', models.IntegerField(help_text='Deslocamento em metros ou quadrados')),
                ('size', models.CharField(help_text='Ex: Médio, Pequeno', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('pvs', models.IntegerField(help_text='Pontos de vida (PV)')),
                ('armor_class', models.IntegerField(help_text='Classe de armadura ou defesa (CA)')),
                ('damage_reduction', models.IntegerField(help_text='Redução de dano (RD)')),
                ('generated_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='Enunciado ou texto da pergunta do quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('str_bonus', models.IntegerField(default=0)),
                ('dex_bonus', models.IntegerField(default=0)),
                ('con_bonus', models.IntegerField(default=0)),
                ('int_bonus', models.IntegerField(default=0)),
                ('wis_bonus', models.IntegerField(default=0)),
                ('cha_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RPGClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_hp_lvl1', models.IntegerField(help_text='Vida no nível 1 (Ex: 6 para Mago, 10 para Guerreiro)')),
                ('hp_per_lvl_after', models.IntegerField(help_text='Vida por nível seguinte (Ex: 4 para Mago, 6 para Guerreiro)')),
                ('base_pm_lvl1', models.IntegerField(help_text='PM no nível 1')),
                ('pm_per_lvl_after', models.IntegerField(help_text='PM por nível seguinte')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeDCharacterSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana_points', models.IntegerField(default=0, help_text='PM para conjuradores arcanos/divinos')),
                ('strength', models.IntegerField(default=10)),
                ('dextery', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ded_spec', to='gerenciador.character')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemCharacterSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=1)),
                ('agility', models.IntegerField(default=1)),
                ('constitution', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('presence', models.IntegerField(default=1)),
                ('effort_points', models.IntegerField(default=0, help_text='Pontos de esforço para utilizar as habilidades')),
                ('sanity', models.IntegerField(help_text='Pontos de sanidade')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_spec', to='gerenciador.character')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('target_attribute', models.CharField(choices=[('STR', 'Strength / Força'), ('DEX', 'Dexterity / Destreza'), ('CON', 'Constitution / Constituição'), ('INT', 'Intelligence / Inteligência'), ('WIS', 'Wisdom / Sabedoria'), ('CHA', 'Charisma / Carisma')], help_text='Atributo que receberá ponto se esta opção for escolhida', max_length=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gerenciador.question')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='suggested_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador.rpgclass'),
        ),
        migrations.AddField(
            model_name='rpgclass',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gerenciador.system'),
        ),
        migrations.AddField(
            model_name='race',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='gerenciador.system'),
        ),
        migrations.AddField(
            model_name='question',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gerenciador.system'),
        ),
        migrations.AddField(
            model_name='character',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='gerenciador.system'),
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_profile', models.CharField(choices=[('FOR', 'Combatente / Direto'), ('DEX', 'Furtivo / Especialista'), ('INT', 'Erudito / Analítico'), ('CHA', 'Social / Diplomata')], help_text='Perfil psicológico do jogador detectado no quiz', max_length=3)),
                ('suggested_class', models.CharField(help_text='Ex: Mago, Combatente, Ocultista', max_length=150)),
                ('roleplay_text', models.TextField(help_text='O conselho prático de como o iniciante pode interpretar esse personagem')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='gerenciador.system')),
            ],
        ),
        migrations.CreateModel(
            name='TormentaCharacterSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana_points', models.IntegerField(default=0, help_text='PM para conjuradores arcanos/divinos')),
                ('strength', models.IntegerField(default=10)),
                ('dextery', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tormenmta_spec', to='gerenciador.character')),
            ],
        ),
    ]
